/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Programa2;

import javax.swing.JOptionPane;

/**
 *
 * @author DAW
 */
public class Programa2 extends javax.swing.JFrame {

    /**
     * Creates new form Programa2
     */
    public Programa2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textPrecio = new javax.swing.JTextField();
        textUnidades = new javax.swing.JTextField();
        textDescuento = new javax.swing.JTextField();
        textIVA = new javax.swing.JTextField();
        labelPrecio = new javax.swing.JLabel();
        labelUnidades = new javax.swing.JLabel();
        labelDescuento = new javax.swing.JLabel();
        labelIVA = new javax.swing.JLabel();
        labelPorcien1 = new javax.swing.JLabel();
        labelPorcien2 = new javax.swing.JLabel();
        botonCalcular = new javax.swing.JButton();
        labelTotal = new javax.swing.JLabel();
        labelTotalEuros = new javax.swing.JLabel();
        labelTotalResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textPrecio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        textUnidades.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        textDescuento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        textIVA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        labelPrecio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelPrecio.setText("Precio artículo");

        labelUnidades.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelUnidades.setText("Unidades");

        labelDescuento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelDescuento.setText("Descuento");

        labelIVA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelIVA.setText("IVA");

        labelPorcien1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelPorcien1.setText("%");

        labelPorcien2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelPorcien2.setText("%");

        botonCalcular.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonCalcular.setText("Calcular");
        botonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcularActionPerformed(evt);
            }
        });

        labelTotal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelTotal.setText("Total");

        labelTotalEuros.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelTotalEuros.setText("€");

        labelTotalResultado.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelTotalResultado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTotalResultado.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelIVA)
                            .addComponent(labelDescuento)
                            .addComponent(labelUnidades)
                            .addComponent(labelPrecio))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(textIVA, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(textDescuento, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(textUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(botonCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(labelTotalResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelTotalEuros, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(labelPorcien2)
                                        .addComponent(labelPorcien1))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(labelTotal)))
                .addGap(72, 72, 72))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelPrecio)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUnidades))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelPorcien1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelPorcien2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(labelDescuento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelIVA)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTotal)
                    .addComponent(labelTotalEuros)
                    .addComponent(labelTotalResultado))
                .addGap(29, 29, 29)
                .addComponent(botonCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcularActionPerformed
       
        try{
            //Primero parseo la string de unidades a int porque si está mal tiene un mensaje de error distinto
            int unidades = Integer.parseInt(textUnidades.getText());
            
            //Si las unidades es un entero entonces sigue
            try{
                //Parseo todas las strings de las cajas de texto a números
                //Si alguno falla por contener letras lanza excepción y sale el diálogo del error de los double
                double precio = Double.parseDouble(textPrecio.getText());
                double descuento = Double.parseDouble(textDescuento.getText());
                double iva = Double.parseDouble(textIVA.getText());
                
                //Si todo ha ido bien calculo el precio final y lo muestro en el Jlabel del resultado
                //El programa está pensado para que en descuento e iva se introduzcan "enteros" como 21(%) 
                //y aquí se convierte en porcentaje
                double preciofinal = (precio*unidades)*(1-(descuento/100))*(1+(iva/100));
                labelTotalResultado.setText(String.format("%.2f", preciofinal));
                
            }catch(NumberFormatException e){
                //Mensaje de error del double
                JOptionPane.showMessageDialog(this, "Algún valor introducido no es un número");
            }catch(Exception e){
                //Mensaje de error genérico
                JOptionPane.showMessageDialog(this, "Algo no ha salido bien");
            }
            
        }catch(NumberFormatException e){
            //Mensaje de error del int
            JOptionPane.showMessageDialog(this, "El número de unidades tiene que ser un número entero");
        }
       
        
    }//GEN-LAST:event_botonCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Programa2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Programa2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Programa2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Programa2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Programa2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCalcular;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelDescuento;
    private javax.swing.JLabel labelIVA;
    private javax.swing.JLabel labelPorcien1;
    private javax.swing.JLabel labelPorcien2;
    private javax.swing.JLabel labelPrecio;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JLabel labelTotalEuros;
    private javax.swing.JLabel labelTotalResultado;
    private javax.swing.JLabel labelUnidades;
    private javax.swing.JTextField textDescuento;
    private javax.swing.JTextField textIVA;
    private javax.swing.JTextField textPrecio;
    private javax.swing.JTextField textUnidades;
    // End of variables declaration//GEN-END:variables
}
